" set Vim-specific sequences for RGB colors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set termguicolors
"color solarized8_high
"set background=dark

"let g:seoul256_background = 236
"color seoul256

" Zenburn theme
" darker background
let g:zenburn_high_Contrast = 1
" less visible line numbers
let g:zenburn_subdued_LineNr = 1
" increase contrast of visual selection
let g:zenburn_alternate_Visual = 1
colors zenburn

syntax enable
"set spell spelllang=en_us
"set spell spelllang=de

"set t_Co=256
set number
set hlsearch
set tabstop=2
set shiftwidth=2
set expandtab
set autoindent
set hidden
set autowrite
set splitbelow
set splitright
set noswapfile

filetype plugin on

let g:UltiSnipsExpandTrigger="<tab>"

" vim-rooter
" Don't message me about change
let g:rooter_silent_chdir = 1

" vim-prosession
" Session per branch
let g:prosession_per_branch = 1

let mapleader=','
"inoremap jk <esc>

" Jump back and forth between last two used buffers
nnoremap <leader><leader> :b#<cr>

" Files, already checked in into git, won't find new files
" output of 'git ls-files'
nnoremap <leader>. :GFiles<cr>

" Files I currently work on (output of 'git status')
" n -> 'new'
nnoremap <leader>n :GFiles?<cr>

nnoremap <leader>- :Files<cr>
nnoremap <leader>e :Explore<cr>
nnoremap <leader><space> :Buffers<cr>
nnoremap <leader>m :Rg<space>

nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" Tab through all buffers
nnoremap <Tab> :bnext<cr>
nnoremap <S-Tab> :bprevious<cr>

command! -bang FinpowerFiles call fzf#vim#files('~/projects/mge/mge-finpowerment', <bang>0)
command! -bang FinpowerClientFiles call fzf#vim#files('~/projects/mge/mge-finpowerment/client/src', <bang>0)
command! -bang FinpowerAppFiles call fzf#vim#files('~/projects/mge/mge-finpowerment/app', <bang>0)

nnoremap <leader>f :FinpowerFiles<cr>
nnoremap <leader>fc :FinpowerClientFiles<cr>
nnoremap <leader>fa :FinpowerApp<cr>

" Search in files in current file's folder
nnoremap <silent> <Leader>pf :Files %:p:h<CR>

" * = search for word under cursor inside current file
" Search for word under cursor across files
nnoremap <silent> <Leader>s :Rg <C-R><C-W><CR>

nnoremap <Space> @q


vnoremap <C-r> "hy:%s/<C-r>h//g<left><left>


"let g:ale_linters={
"\   'javascript': ['eslint']
"\}

"let g:ale_fixers={
"\   'javascript': ['prettier'],
"\   'css': ['prettier'],
"\}

"let g:ale_linters_explicit=1
"let g:ale_fix_on_save=1

"command! -nargs=0 Prettier :call CocAction('runCommand', 'prettier.formatFile')

